// Saturday Dynasty Football - browser-only paid editor tools.
// Uses the game's normal compact save/hydration path so Android remains untouched.
(() => {
  'use strict';
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const clamp=(n,a,b)=>Math.max(a,Math.min(b,Number(n)||0));
  const POS=['QB','RB','WR','TE','OT','IOL','EDGE','DL','LB','CB','S','K','P'];
  const ARCH={QB:['Field General','Improviser','Scrambler'],RB:['Power Back','Elusive Back','Receiving Back'],WR:['Deep Threat','Route Runner','Physical'],TE:['Vertical Threat','Blocking','Possession'],OT:['Pass Protector','Power'],IOL:['Power','Agile'],EDGE:['Speed Rusher','Power Rusher','Run Stopper'],DL:['Run Stopper','Power Rusher'],LB:['Field General','Coverage','Run Stopper'],CB:['Man Cover','Zone Cover','Slot'],S:['Zone','Hybrid','Run Support'],K:['Accurate','Power'],P:['Directional','Power','Coffin Corner']};
  const DEV=['Normal','Impact','Star','Elite'];
  let work=null,activePlayerId=null;
  const rel=()=>window.SDF_RELEASE_TEST;
  const ent=()=>window.SDF_COMMERCE?.getEntitlements?.()||null;
  const owns=k=>!!(ent()&&(ent().commissioner_mode||ent()[k]));
  const snapshot=()=>rel()?.compactState?.()||null;
  function begin(){work=snapshot();return work}
  function current(){return work}
  async function ensureOwned(k){if(owns(k))return true;await window.SDF_COMMERCE?.refreshEntitlements?.(true);if(owns(k))return true;window.SDF_COMMERCE?.openShop?.();return false}
  function commit(reason){if(!work)return false;const r=rel();if(!r?.hydrateState||!r?.saveNow)return false;r.hydrateState(work);work=null;window.renderAll?.();r.saveNow(reason,true,true);window.dispatchEvent(new CustomEvent('sdf:editor-saved',{detail:{reason}}));return true}

  const st=document.createElement('style');st.id='sdf-paid-editors-style';st.textContent=`
  .sdf-paid-tool{display:inline-flex;align-items:center;gap:7px;border:1px solid #b4943f;border-radius:7px;background:#171e25;color:#f7d873;padding:9px 12px;font-size:.68rem;font-weight:900;letter-spacing:.04em;cursor:pointer}.sdf-paid-tool.locked{border-color:#314656;color:#8ba0ad;background:#0b1922}
  #sdfEditorOverlay{position:fixed;inset:0;z-index:24000;display:none;align-items:center;justify-content:center;padding:18px;background:#02080dcc;backdrop-filter:blur(7px)}#sdfEditorOverlay.open{display:flex}#sdfEditorBox{width:min(1060px,97vw);max-height:93vh;overflow:auto;border:1px solid #315268;border-radius:14px;background:#071722;color:#edf8ff;box-shadow:0 30px 100px #000a;font-family:system-ui}
  .sdf-ed-head{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;padding:20px 22px 14px;border-bottom:1px solid #ffffff12}.sdf-ed-head h2{margin:3px 0 4px;font-size:24px}.sdf-ed-head p{margin:0;color:#8fa6b4;font-size:12px}.sdf-ed-ey{font-size:9px;font-weight:900;letter-spacing:.16em;color:#f1c95c}.sdf-ed-close{border:0;border-radius:7px;background:#112b3a;color:#eef7fb;width:36px;height:36px;font-size:20px;cursor:pointer}
  .sdf-ed-body{padding:16px 22px 22px}.sdf-ed-grid{display:grid;grid-template-columns:300px minmax(0,1fr);gap:15px}.sdf-ed-panel{border:1px solid #1d3a4c;border-radius:10px;background:#0a1d29;padding:14px}.sdf-ed-panel h3{margin:0 0 10px;font-size:14px}.sdf-ed-search{width:100%;box-sizing:border-box;margin-bottom:8px;min-height:40px;border:1px solid #284b60;border-radius:6px;background:#06131c;color:#eff9ff;padding:8px 10px}.sdf-player-list{display:grid;gap:5px;max-height:58vh;overflow:auto}.sdf-player-row{display:flex;justify-content:space-between;gap:10px;text-align:left;border:1px solid #173445;border-radius:7px;background:#071722;color:#dcebf3;padding:8px 9px;cursor:pointer}.sdf-player-row.active{border-color:#d0aa44;background:#18232b}.sdf-player-row small{color:#809aa9}
  .sdf-form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:11px}.sdf-form label{display:grid;gap:5px;color:#90a9b7;font-size:10px;font-weight:800;letter-spacing:.03em}.sdf-form input,.sdf-form select{box-sizing:border-box;width:100%;min-height:40px;border:1px solid #284b60;border-radius:6px;background:#06131c;color:#eff9ff;padding:8px 9px}.sdf-form .wide{grid-column:1/-1}.sdf-form-section{grid-column:1/-1;margin-top:4px;padding-top:10px;border-top:1px solid #ffffff0e;color:#e5f2f8;font-size:11px;font-weight:900;letter-spacing:.08em}.sdf-ed-actions{display:flex;flex-wrap:wrap;justify-content:flex-end;gap:8px;margin-top:15px}.sdf-ed-actions button{min-height:40px;border:0;border-radius:7px;padding:8px 13px;font-weight:900;cursor:pointer}.sdf-save{background:#188875;color:#fff}.sdf-secondary{background:#183343;color:#cce2ed}#sdfEditorToast{min-height:18px;margin:0 0 10px;font-size:11px;color:#91a9b6}#sdfEditorToast.good{color:#6fe0c1}#sdfEditorToast.bad{color:#ff9aaa}
  html.sdf-no-ads [data-sdf-forced-ad],html.sdf-no-ads .sdf-forced-ad{display:none!important}
  @media(max-width:760px){#sdfEditorOverlay{padding:7px}.sdf-ed-body{padding:12px}.sdf-ed-grid{grid-template-columns:1fr}.sdf-player-list{max-height:220px}.sdf-form{grid-template-columns:1fr}.sdf-form .wide,.sdf-form-section{grid-column:1}.sdf-ed-head{padding:15px}.sdf-paid-tool{min-height:42px}}
  `;document.head.appendChild(st);

  function makeOverlay(){if($('#sdfEditorOverlay'))return;const e=document.createElement('div');e.id='sdfEditorOverlay';e.innerHTML=`<section id="sdfEditorBox" role="dialog" aria-modal="true"><header class="sdf-ed-head"><div><div class="sdf-ed-ey">COMMISSIONER TOOLS</div><h2 id="sdfEditorTitle"></h2><p id="sdfEditorSubtitle"></p></div><button class="sdf-ed-close">×</button></header><div class="sdf-ed-body"><div id="sdfEditorToast"></div><div id="sdfEditorContent"></div></div></section>`;document.body.append(e);$('.sdf-ed-close',e).onclick=close;e.onclick=x=>{if(x.target===e)close()}}
  function close(){work=null;$('#sdfEditorOverlay')?.classList.remove('open')}
  function show(title,sub,html){makeOverlay();$('#sdfEditorTitle').textContent=title;$('#sdfEditorSubtitle').textContent=sub;$('#sdfEditorContent').innerHTML=html;$('#sdfEditorToast').textContent='';$('#sdfEditorToast').className='';$('#sdfEditorOverlay').classList.add('open')}
  function toast(t,bad=false){const x=$('#sdfEditorToast');if(!x)return;x.textContent=t;x.className=bad?'bad':'good';clearTimeout(toast.t);toast.t=setTimeout(()=>{if(x)x.className=''},2200)}

  function pfind(id){return current()?.roster?.find(p=>String(p.id)===String(id))}
  function archOptions(pos,cur){return(ARCH[pos]||[]).map(a=>`<option ${a===cur?'selected':''}>${esc(a)}</option>`).join('')}
  function renderPlayerForm(){const p=pfind(activePlayerId),h=$('#sdfPlayerForm');if(!p||!h)return;const a=p.attrs||{};h.innerHTML=`<div class="sdf-form">
    <label class="wide">PLAYER NAME<input id="peName" maxlength="32" value="${esc(p.name)}"></label>
    <label>POSITION<select id="pePos">${POS.map(x=>`<option ${x===p.pos?'selected':''}>${x}</option>`).join('')}</select></label><label>ARCHETYPE<select id="peArch">${archOptions(p.pos,p.arch)}</select></label>
    <label>CLASS / YEAR<select id="peYear">${[1,2,3,4].map(y=>`<option value="${y}" ${Number(p.year)===y?'selected':''}>Year ${y}</option>`).join('')}</select></label><label>DEVELOPMENT<select id="peDev">${DEV.map(d=>`<option ${d===p.dev?'selected':''}>${d}</option>`).join('')}</select></label>
    <label>OVERALL<input id="peOvr" type="number" min="40" max="99" value="${clamp(p.ovr,40,99)}"></label><label>POTENTIAL<input id="pePot" type="number" min="40" max="99" value="${clamp(p.pot,40,99)}"></label><label>MORALE<input id="peMorale" type="number" min="0" max="99" value="${clamp(p.morale,0,99)}"></label><label>HOMETOWN<input id="peHome" maxlength="42" value="${esc(p.hometown||'')}"></label>
    <div class="sdf-form-section">CORE ATTRIBUTES</div><label>SPEED<input id="peSpeed" type="number" min="35" max="99" value="${clamp(a.speed??p.ovr,35,99)}"></label><label>STRENGTH<input id="peStrength" type="number" min="35" max="99" value="${clamp(a.strength??p.ovr,35,99)}"></label><label>SKILL<input id="peSkill" type="number" min="35" max="99" value="${clamp(a.skill??p.ovr,35,99)}"></label><label>AWARENESS<input id="peAware" type="number" min="35" max="99" value="${clamp(a.awareness??p.ovr,35,99)}"></label>
    </div><div class="sdf-ed-actions"><button id="peHeal" class="sdf-secondary">Heal Injury</button><button id="peSave" class="sdf-save">Save Player</button></div>`;
    $('#pePos').onchange=e=>$('#peArch').innerHTML=archOptions(e.target.value,'');$('#peHeal').onclick=()=>{p.injury=null;const id=p.id,name=p.name;if(commit(`Player Editor healed ${name}`)){openPlayerEditor(id,true);setTimeout(()=>toast(`${name} is healthy.`),0)}};$('#peSave').onclick=savePlayer}
  function savePlayer(){const s=current(),p=pfind(activePlayerId);if(!s||!p)return;const name=($('#peName').value||'').trim();if(!name)return toast('Player name is required.',true);const oldPos=p.pos;p.name=name.slice(0,32);p.pos=$('#pePos').value;p.arch=$('#peArch').value||(ARCH[p.pos]||['Balanced'])[0];p.year=clamp($('#peYear').value,1,4);p.dev=$('#peDev').value;p.ovr=clamp($('#peOvr').value,40,99);p.pot=Math.max(p.ovr,clamp($('#pePot').value,40,99));p.morale=clamp($('#peMorale').value,0,99);p.hometown=($('#peHome').value||'').trim().slice(0,42);p.attrs=p.attrs||{};p.attrs.speed=clamp($('#peSpeed').value,35,99);p.attrs.strength=clamp($('#peStrength').value,35,99);p.attrs.skill=clamp($('#peSkill').value,35,99);p.attrs.awareness=clamp($('#peAware').value,35,99);if(oldPos!==p.pos){p.starter=false;s.depthChart={}}s.news=s.news||[];s.news.push(`Commissioner Mode edited ${p.name}: ${p.pos}, ${p.ovr} OVR, ${p.pot} potential.`);const id=p.id,n=p.name;if(commit(`Player Editor: ${n}`)){openPlayerEditor(id,true);setTimeout(()=>toast(`${n} saved.`),0)}}
  async function openPlayerEditor(id=null,skip=false){if(!skip&&!(await ensureOwned('player_editor')))return;const s=begin();if(!s?.school||!Array.isArray(s.roster)){work=null;return alert('Load a dynasty before opening Player Editor.')}const ps=s.roster.slice().sort((a,b)=>POS.indexOf(a.pos)-POS.indexOf(b.pos)||Number(b.ovr)-Number(a.ovr));activePlayerId=id&&ps.some(p=>String(p.id)===String(id))?id:(ps[0]?.id);show('Player Editor',`${s.school.name} · edit roster identity, ratings and development`,`<div class="sdf-ed-grid"><aside class="sdf-ed-panel"><h3>Roster</h3><input id="peSearch" class="sdf-ed-search" type="search" placeholder="Search player or position"><div class="sdf-player-list">${ps.map(p=>`<button class="sdf-player-row ${String(p.id)===String(activePlayerId)?'active':''}" data-id="${esc(p.id)}" data-q="${esc(`${p.name} ${p.pos} ${p.hometown||''}`.toLowerCase())}"><span><b>${esc(p.name)}</b><br><small>${p.pos} · Year ${p.year}</small></span><strong>${p.ovr}</strong></button>`).join('')}</div></aside><section id="sdfPlayerForm" class="sdf-ed-panel"></section></div>`);$('#peSearch').oninput=e=>{$$('.sdf-player-row').forEach(b=>b.hidden=!b.dataset.q.includes(e.target.value.trim().toLowerCase()))};$$('.sdf-player-row').forEach(b=>b.onclick=()=>{activePlayerId=b.dataset.id;$$('.sdf-player-row').forEach(x=>x.classList.toggle('active',x===b));renderPlayerForm()});renderPlayerForm()}

  function teamHtml(s){const c=s.school,t=s.stadium||{};return`<section class="sdf-ed-panel"><div class="sdf-form">
    <label class="wide">PROGRAM NAME<input id="teName" maxlength="38" value="${esc(c.name)}"></label><label>CITY<input id="teCity" maxlength="28" value="${esc(c.city||'')}"></label><label>STATE<input id="teState" maxlength="3" value="${esc(c.state||'')}"></label>
    <div class="sdf-form-section">PROGRAM RATINGS</div><label>PRESTIGE<input id="tePrestige" type="number" min="20" max="99" value="${clamp(c.prestige,20,99)}"></label><label>RECENT SUCCESS<input id="teRecent" type="number" min="20" max="99" value="${clamp(c.recent,20,99)}"></label><label>FACILITIES REPUTATION<input id="teFacilities" type="number" min="20" max="99" value="${clamp(c.facilities,20,99)}"></label><label>PRO PIPELINE<input id="tePro" type="number" min="20" max="99" value="${clamp(c.pro,20,99)}"></label><label>NIL REPUTATION<input id="teNil" type="number" min="20" max="99" value="${clamp(c.nil,20,99)}"></label><label>ACADEMICS<input id="teAcademics" type="number" min="20" max="99" value="${clamp(c.academics,20,99)}"></label>
    <div class="sdf-form-section">STADIUM & RESOURCES</div><label>STADIUM NAME<input id="teStadium" maxlength="40" value="${esc(t.name||'Memorial Stadium')}"></label><label>CAPACITY<input id="teCapacity" type="number" min="10000" max="150000" step="500" value="${clamp(t.capacity||55000,10000,150000)}"></label><label>PROGRAM FUNDS ($)<input id="teBudget" type="number" min="0" max="100000000" step="10000" value="${Math.max(0,Math.round(Number(s.budget)||0))}"></label><label>RECRUITING NIL POOL ($)<input id="teNilBudget" type="number" min="0" max="100000000" step="1000" value="${Math.max(0,Math.round(Number(s.nilBudget)||0))}"></label>
    </div><div class="sdf-ed-actions"><button id="teSave" class="sdf-save">Save Team</button></div></section>`}
  function saveTeam(){const s=current();if(!s?.school)return;const c=s.school,old=c.name;c.name=($('#teName').value||old).trim().slice(0,38)||old;c.city=($('#teCity').value||c.city||'').trim().slice(0,28);c.state=($('#teState').value||c.state||'').trim().toUpperCase().slice(0,3);c.prestige=clamp($('#tePrestige').value,20,99);c.recent=clamp($('#teRecent').value,20,99);c.facilities=clamp($('#teFacilities').value,20,99);c.pro=clamp($('#tePro').value,20,99);c.nil=clamp($('#teNil').value,20,99);c.academics=clamp($('#teAcademics').value,20,99);s.stadium=s.stadium||{};s.stadium.name=($('#teStadium').value||'Memorial Stadium').trim().slice(0,40);s.stadium.capacity=clamp($('#teCapacity').value,10000,150000);s.budget=clamp($('#teBudget').value,0,100000000);s.nilBudget=clamp($('#teNilBudget').value,0,100000000);const sync=t=>{if(t&&Number(t.id)===Number(c.id))Object.assign(t,{name:c.name,conference:c.conference,prestige:c.prestige,recent:c.recent})};(s.world||[]).forEach(sync);(s.rankings||[]).forEach(sync);(s.standings||[]).forEach(sync);s.news=s.news||[];s.news.push(`Commissioner Mode updated ${c.name}'s program profile.`);const n=c.name;if(commit(`Team Editor: ${n}`)){openTeamEditor(true);setTimeout(()=>toast(`${n} saved.`),0)}}
  async function openTeamEditor(skip=false){if(!skip&&!(await ensureOwned('team_editor')))return;const s=begin();if(!s?.school){work=null;return alert('Load a dynasty before opening Team Editor.')}show('Team Editor',`${s.school.name} · customize program ratings, resources and stadium`,teamHtml(s));$('#teSave').onclick=saveTeam}

  function inject(){const rh=$('#rosterTab .surface .section-head .actions');if(rh&&!$('#sdfPlayerEditorBtn')){const b=document.createElement('button');b.id='sdfPlayerEditorBtn';b.className='sdf-paid-tool';b.type='button';b.onclick=()=>openPlayerEditor();rh.append(b)}const th=$('#teamTab .surface .section-head');if(th&&!$('#sdfTeamEditorBtn')){const b=document.createElement('button');b.id='sdfTeamEditorBtn';b.className='sdf-paid-tool';b.type='button';b.onclick=()=>openTeamEditor();th.append(b)}update()}
  function update(){const p=$('#sdfPlayerEditorBtn'),t=$('#sdfTeamEditorBtn');if(p){const ok=owns('player_editor');p.classList.toggle('locked',!ok);p.textContent=ok?'✦ PLAYER EDITOR':'🔒 PLAYER EDITOR'}if(t){const ok=owns('team_editor');t.classList.toggle('locked',!ok);t.textContent=ok?'✦ TEAM EDITOR':'🔒 TEAM EDITOR'}document.documentElement.classList.toggle('sdf-no-ads',owns('remove_ads'));$$('[data-sdf-forced-ad],.sdf-forced-ad').forEach(x=>x.hidden=owns('remove_ads'))}
  window.SDF_COMMISSIONER={openPlayerEditor,openTeamEditor,hasPlayerEditor:()=>owns('player_editor'),hasTeamEditor:()=>owns('team_editor'),removeAds:()=>owns('remove_ads')};window.SDF_AD_POLICY={shouldShowForcedAds:()=>!owns('remove_ads'),mayOfferRewardedAds:()=>true};window.addEventListener('sdf:entitlements',()=>{inject();update()});const init=()=>{makeOverlay();inject();update()};document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();
