-- Saturday Dynasty Football browser commerce schema
-- Run this in Supabase SQL Editor after supabase.sql.
-- Safe to run more than once.

create table if not exists public.user_entitlements (
  user_id uuid primary key references auth.users(id) on delete cascade,
  remove_ads boolean not null default false,
  player_editor boolean not null default false,
  team_editor boolean not null default false,
  commissioner_mode boolean not null default false,
  updated_at timestamptz not null default now()
);

create table if not exists public.purchase_ledger (
  id bigint generated by default as identity primary key,
  stripe_session_id text not null unique,
  user_id uuid not null references auth.users(id) on delete cascade,
  product_key text not null check (product_key in ('remove_ads','player_editor','team_editor','commissioner_mode')),
  price_id text not null,
  amount_total bigint,
  currency text,
  purchased_at timestamptz not null default now()
);

alter table public.user_entitlements enable row level security;
alter table public.purchase_ledger enable row level security;

drop policy if exists "read own entitlements" on public.user_entitlements;
create policy "read own entitlements" on public.user_entitlements
for select to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "read own purchases" on public.purchase_ledger;
create policy "read own purchases" on public.purchase_ledger
for select to authenticated
using ((select auth.uid()) = user_id);

-- Do not add INSERT/UPDATE/DELETE policies for authenticated users.
-- Purchases are granted only by the signed Stripe webhook using the admin client.

create or replace function public.grant_sdf_entitlement(
  p_user_id uuid,
  p_product_key text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_product_key not in ('remove_ads','player_editor','team_editor','commissioner_mode') then
    raise exception 'Unknown Saturday Dynasty product: %', p_product_key;
  end if;

  insert into public.user_entitlements (
    user_id,
    remove_ads,
    player_editor,
    team_editor,
    commissioner_mode,
    updated_at
  ) values (
    p_user_id,
    p_product_key in ('remove_ads','commissioner_mode'),
    p_product_key in ('player_editor','commissioner_mode'),
    p_product_key in ('team_editor','commissioner_mode'),
    p_product_key = 'commissioner_mode',
    now()
  )
  on conflict (user_id) do update set
    remove_ads = public.user_entitlements.remove_ads or excluded.remove_ads,
    player_editor = public.user_entitlements.player_editor or excluded.player_editor,
    team_editor = public.user_entitlements.team_editor or excluded.team_editor,
    commissioner_mode = public.user_entitlements.commissioner_mode or excluded.commissioner_mode,
    updated_at = now();
end;
$$;

revoke all on function public.grant_sdf_entitlement(uuid,text) from public;
revoke all on function public.grant_sdf_entitlement(uuid,text) from anon;
revoke all on function public.grant_sdf_entitlement(uuid,text) from authenticated;
grant execute on function public.grant_sdf_entitlement(uuid,text) to service_role;

create index if not exists purchase_ledger_user_id_idx on public.purchase_ledger(user_id);
create index if not exists purchase_ledger_purchased_at_idx on public.purchase_ledger(purchased_at desc);
