const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),{stripTypeScriptTypes}=require('node:module');
const code=stripTypeScriptTypes(fs.readFileSync(require('node:path').join(__dirname,'../supabase/functions/usage-reporting/index.ts'),'utf8'));
function setup(){let handler;const calls=[];const c={Deno:{serve:f=>handler=f,env:{get:k=>({SUPABASE_URL:'https://test.invalid',SUPABASE_SERVICE_ROLE_KEY:'server-secret',RESEND_API_KEY:'email-secret'}[k])}},Request,Response,Set,Date,JSON,TextEncoder,Uint8Array,crypto:require('node:crypto').webcrypto,fetch:async(url,opts)=>{calls.push({url,opts});return Response.json({ok:true})}};vm.runInNewContext(code,c);return{handler,calls,c}}
test('Public events validate allowlist, hash device, omit arbitrary user data',async()=>{
 const h=setup(),device=crypto.randomUUID();const r=await h.handler(new Request('https://test.invalid',{method:'POST',headers:{origin:'https://saturdaydynasty.ctoolis.workers.dev'},body:JSON.stringify({action:'events',device,platform:'android',events:[{id:crypto.randomUUID(),event:'game_completed',at:new Date().toISOString(),save:'never upload this'}]})}));assert.equal(r.status,200);const body=JSON.parse(h.calls[0].opts.body);assert.match(body.p_device,/^[a-f0-9]{64}$/);assert.notEqual(body.p_device,device);assert.equal(body.p_events[0].save,undefined);assert.equal(body.p_events[0].event,'game_completed');
});
test('Disallowed origin, malformed events and unauthenticated report cannot trigger mail',async()=>{
 const h=setup();for(const [p,origin,status] of [[{action:'report'},'',401],[{action:'events'},'https://bad.invalid',403],[{action:'events',device:crypto.randomUUID(),platform:'browser',events:[{event:'full_save'}]},'',400]]){const r=await h.handler(new Request('https://test.invalid',{method:'POST',headers:{origin},body:JSON.stringify(p)}));assert.equal(r.status,status)}assert.equal(h.calls.length,0);
});
test('Email totals separate 24h/all-time, platforms, ad impressions and products',()=>{
 const h=setup(),now=new Date().toISOString();h.c.fixture={key:'test',test:true,from:now,to:now,started_at:now,devices:[],active:[],last24:[{platform:'android',event:'game_completed',total:3},{platform:'browser',event:'purchase_confirmed',product:'commissioner_mode',total:1}],alltime:[{platform:'android',event:'game_completed',total:70},{platform:'android',event:'reward_shown',total:2},{platform:'android',event:'interstitial_shown',total:5}]};const report=vm.runInNewContext('formatReport(fixture)',h.c);assert.match(report.text,/Games completed: 3 \| 70/);assert.match(report.text,/Ads shown: 0 \| 7/);assert.match(report.text,/commissioner_mode purchases: 1 \| 0/);assert.deepEqual(Array.from(report.to),['ctoolis@gmail.com']);assert.match(report.text,/not Google Play install totals/);
});

test('Basic events omit device identity while preserving deduplication IDs',async()=>{
 const h=setup(),id=crypto.randomUUID();const r=await h.handler(new Request('https://test.invalid',{method:'POST',body:JSON.stringify({action:'events',platform:'browser',events:[{id,event:'reporting_started',at:new Date().toISOString()}]})}));assert.equal(r.status,200);const body=JSON.parse(h.calls[0].opts.body);assert.equal(body.p_device,null);assert.equal(body.p_events[0].id,id);
});
test('Malformed supplied device ID is rejected instead of treated as basic',async()=>{
 const h=setup();for(const device of ['',123,'not-a-uuid']){const r=await h.handler(new Request('https://test.invalid',{method:'POST',body:JSON.stringify({action:'events',device,platform:'browser',events:[{id:crypto.randomUUID(),event:'session',at:new Date().toISOString()}]})}));assert.equal(r.status,400)}assert.equal(h.calls.length,0);
});

test('Scenario milestones are accepted as basic events without a tracking identifier',async()=>{const h=setup();const r=await h.handler(new Request('https://test.invalid',{method:'POST',body:JSON.stringify({action:'events',platform:'android',events:['scenario_started','scenario_completed','scenario_ended','first_season_finished','first_game_under_5m','first_game_under_15m','first_game_over_15m'].map(event=>({id:crypto.randomUUID(),event,at:new Date().toISOString()}))})}));assert.equal(r.status,200);assert.equal(JSON.parse(h.calls[0].opts.body).p_device,null)});
test('Retention email uses mature cohort denominators and does not divide zero',()=>{const h=setup(),now=new Date().toISOString();h.c.fixture={from:now,to:now,started_at:now,devices:[],active:[],last24:[],alltime:[],retention:[{platform:'android',eligible1:10,returned1:3,eligible7:0,returned7:0}]};const report=vm.runInNewContext('formatReport(fixture)',h.c);assert.match(report.text,/3\/10 \(30.0%\)/);assert.match(report.text,/Not enough elapsed time/);assert.match(report.text,/not all installs/);assert.doesNotMatch(report.text,/NaN|Infinity/)});
